# Generated by Django 5.2.14 on 2026-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investdev_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='picture',
            field=models.ImageField(blank=True, upload_to='publications/%Y/%m'),
        ),
    ]
