# Generated by Django 5.2.14 on 2026-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investdev_app', '0002_publication_slug_alter_publication_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
