# Generated by Django 5.2.14 on 2026-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investdev_app', '0003_alter_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
