# Generated by Django 5.2.8 on 2026-05-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investdev_app', '0006_alter_publication_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='investdev_app.category'),
        ),
        migrations.AddField(
            model_name='publication',
            name='factors',
            field=models.ManyToManyField(blank=True, related_name='publications', to='investdev_app.investmentfactor'),
        ),
    ]
