# Generated by Django 5.2.8 on 2026-05-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investdev_app', '0007_investmentfactor_alter_publication_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('initiator', models.CharField(max_length=100)),
                ('budget_mln_rub', models.IntegerField(blank=True, null=True)),
                ('horizon_years', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication', to='investdev_app.projectpassport'),
        ),
    ]
