# Generated by Django 5.2.8 on 2026-05-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investdev_app', '0008_projectpassport_publication_passport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='investmentfactor',
            options={'ordering': ['id'], 'verbose_name': 'Инвестиционный фактор', 'verbose_name_plural': 'Инвестиционные факторы'},
        ),
        migrations.AlterModelOptions(
            name='projectpassport',
            options={'ordering': ['id'], 'verbose_name': 'Паспорт проекта', 'verbose_name_plural': 'Паспорта проектов'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='investmentfactor',
            name='factor',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Фактор'),
        ),
        migrations.AlterField(
            model_name='investmentfactor',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='projectpassport',
            name='budget_mln_rub',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бюджет (млн руб.)'),
        ),
        migrations.AlterField(
            model_name='projectpassport',
            name='horizon_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Горизонт (лет)'),
        ),
        migrations.AlterField(
            model_name='projectpassport',
            name='initiator',
            field=models.CharField(max_length=100, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='projectpassport',
            name='project_code',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Код проекта'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='investdev_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='factors',
            field=models.ManyToManyField(blank=True, related_name='publications', to='investdev_app.investmentfactor', verbose_name='Факторы'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication', to='investdev_app.projectpassport', verbose_name='Паспорт проекта'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='picture',
            field=models.ImageField(blank=True, upload_to='publications/%Y/%m', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
